### ISSUE TITLE
incorrect md5 and sha256 values for 

### ISSUE THREAD

**Issue by cyboflash** [Xilinx/meta-virtualization#2]
MD5 and SHA256 values for protobuf-3.0.0.tar.gz are incorrect. They should be 41f2934b451a82115ccc4aa1f9b156f2 and 44e36eee53a7bc8b88935b105c8e2773f6ae9f89e3f25e95f93c4bcac908bb98 respectively

https://github.com/Xilinx/meta-virtualization/blob/cbfd4376d5e9d229f857151ffdfb57fbc6c0c40d/recipes-devtools/protobuf/protobuf_3.0.0.bb#L14-L15

**Comment by mharth** [comment]
Use mirror url for 2017.x release
SOURCE_MIRROR_URL ?= "http://petalinux.xilinx.com/sswreleases/rel-v2017.x/downloads"
INHERIT += "own-mirrors"

where x is xilinx release version

**Comment by cyboflash** [comment]
@mharth I tried to going to http://petalinux.xilinx.com/sswreleases/rel-v2017.3/downloads and got a 404 Not Found error. 
<img width="797" alt="screen shot 2017-11-09 at 11 32 15 am" src="https://user-images.githubusercontent.com/2373916/32625686-c5b4d4de-c541-11e7-9296-071c8714e97e.png">

I have also verified http://petalinux.xilinx.com/sswreleases/rel-v2017.1/downloads and http://petalinux.xilinx.com/sswreleases/rel-v2017.2/downloads. I get the same error

Are you sure the link is correct?

**Comment by mharth** [comment]
It is not accessible manually, please add the lines in your build
https://github.com/Xilinx/meta-petalinux/blob/rel-v2017.3/conf/local.conf.sample#L202-L203

**Comment by cyboflash** [comment]
@mharth Tried it. Getting an error, saying that it cannot fetch it.

**Comment by mharth** [comment]
Try wget http://petalinux.xilinx.com/sswreleases/rel-v2017.3/downloads/protobuf-3.0.0.tar.gz
I just tested it, please check your proxy settings as well

**Comment by cyboflash** [comment]
@mharth That one works. Thanks.
